# SPDX-FileCopyrightText: 2024 Luflosi <zonewatch@luflosi.de>
# SPDX-License-Identifier: CC0-1.0

name: "CI"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@e4fb5e65d88bc1ed7f248eda4e6645126ed90438
      - uses: DeterminateSystems/flake-checker-action@673506c3ec8a438a0c5a1d62ad852f55e596e440
      - uses: cachix/cachix-action@29121a2db12c7ff8b89724a8898ca20d33bb4ea3
        with:
          name: luflosi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix flake check`
        run: nix flake check --all-systems -L
