# SPDX-FileCopyrightText: 2024 Luflosi <zonewatch@luflosi.de>
# SPDX-License-Identifier: CC0-1.0

name: "CI"
on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flake-checker-action@main
      - uses: cachix/cachix-action@41f25c0d23388f1a854cc67abb62029877468386
        with:
          name: luflosi
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run `nix flake check`
        run: nix flake check --all-systems -L
